{% set name = "msitools" %}
{% set version = "0.103" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/msitools/{{ version }}/msitools-{{ version }}.tar.xz
  sha256: d17622eebbf37fa4c09b59be0bc8db08b26be300a6731c74da1ebce262bce839
  patches:
    - 0001-Look-for-vapi-files-in-prefix.patch

build:
  number: 0
  # Not supported on win
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - bison
    - flex
    - pkg-config
    - meson
    - vala
    - gobject-introspection
    - perl *
    - glib    # [build_platform != target_platform]
    - gcab    # [build_platform != target_platform]
    - libgsf  # [build_platform != target_platform]
  host:
    - libgsf
    - libuuid
    - libxml2
    - gcab
    - glib
    - gettext
  run:
    - {{ pin_compatible("libgsf", max_pin="x.x") }}

test:
  commands:
    - test -f $PREFIX/include/libmsi-1.0/libmsi.h
    - test -f $PREFIX/lib/libmsi-1.0${SHLIB_EXT}
    - msiextract --help

about:
  home: https://wiki.gnome.org/msitools
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - copyright
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  doc_url: https://wiki.gnome.org/msitools/HowTo/CreateLibraryWxi
  dev_url: https://gitlab.gnome.org/GNOME/msitools

extra:
  recipe-maintainers:
    - isuruf
    - xhochy
