{% set name = "msitools" %}
{% set version = "0.100" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/msitools/{{ version }}/msitools-{{ version }}.tar.xz
  sha256: bbf1a6e3a9c2323b860a3227ac176736a3eafc4a44a67346c6844591f10978ea
  patches:
    - byte-order-osx.patch

build:
  number: 3
  # Not supported on win
  skip: True   # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
    - bison
    - flex
    - pkg-config
  host:
    - libgsf
    - libuuid
    - libxml2
    - gcab
    - glib
  run:
    - {{ pin_compatible("libgsf", max_pin="x.x") }}

test:
  commands:
    - test -f $PREFIX/include/libmsi-1.0/libmsi.h
    - test -f $PREFIX/lib/libmsi${SHLIB_EXT}
    - msiextract --help

about:
  home: https://wiki.gnome.org/msitools
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING.LIB
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  doc_url: https://wiki.gnome.org/msitools/HowTo/CreateLibraryWxi
  dev_url: https://gitlab.gnome.org/GNOME/msitools

extra:
  recipe-maintainers:
    - isuruf
    - xhochy
